#include "app/Strings.h"

namespace citron {

namespace {

Strings english() {
    Strings s;
    s.tabPlay = L"Play";
    s.tabVersions = L"Versions";
    s.tabSettings = L"Settings";
    s.launcher = L"Launcher";
    s.toggleTheme = L"Toggle theme";
    s.minimize = L"Minimize";
    s.maximize = L"Maximize";
    s.restore = L"Restore";
    s.close = L"Close";
    s.gameName = L"Minecraft Bedrock";
    s.launch = L"Launch";
    s.launching = L"Launching…";
    s.manageVersions = L"Manage versions";
    s.noVersion = L"No version";
    s.noVersionHint = L"Install a version from the Versions page to get started.";
    s.downloadingUpper = L"DOWNLOADING";
    s.searchVersion = L"Search version…";
    s.refresh = L"Refresh";
    s.filterAll = L"All";
    s.filterRelease = L"Release";
    s.filterPreview = L"Preview";
    s.filterInstalled = L"Installed";
    s.release = L"Release";
    s.preview = L"Preview";
    s.statusInstalled = L"Installed";
    s.statusDownloaded = L"Downloaded";
    s.statusNotDownloaded = L"Not downloaded";
    s.statusDownloading = L"Downloading";
    s.statusVerifying = L"Verifying";
    s.statusExtracting = L"Extracting";
    s.statusRemoving = L"Deleting";
    s.statusActive = L"Active";
    s.statusFailed = L"Failed";
    s.statusUnavailable = L"Unavailable";
    s.download = L"Download";
    s.install = L"Install";
    s.cancel = L"Cancel";
    s.remove = L"Delete";
    s.confirmRemove = L"Confirm delete";
    s.retry = L"Retry";
    s.dismiss = L"Dismiss";
    s.noResults = L"No versions match.";
    s.versionsEmpty = L"The version list could not be loaded.";
    s.settingsUpper = L"SETTINGS";
    s.pathsUpper = L"PATHS";
    s.aboutUpper = L"ABOUT";
    s.language = L"Language";
    s.languageSub = L"Launcher interface language";
    s.closeOnLaunch = L"Close launcher on game start";
    s.closeOnLaunchSub = L"The launcher exits once Minecraft is running";
    s.checkUpdates = L"Check for launcher updates";
    s.checkUpdatesSub = L"Notify when a new Citron Launcher version is available";
    s.rootDir = L"Root directory";
    s.browse = L"Browse…";
    s.installers = L"Installers";
    s.logs = L"Logs";
    s.apply = L"Apply";
    s.reset = L"Reset";
    s.aboutSub = L"A minimal launcher for Minecraft Bedrock Edition";
    s.upToDate = L"Up to date";
    s.updateAvailable = L"Update available";
    s.updateFailed = L"Could not check";
    s.notChecked = L"Not checked yet";
    s.checkedAgo = L"Checked {}";
    s.checkNow = L"Check now";
    s.checking = L"Checking…";
    s.links = L"Links";
    s.toastLaunch = L"Launching Minecraft";
    s.toastSelect = L"Active version:";
    s.toastInstalled = L"Installed:";
    s.toastDownloaded = L"Downloaded:";
    s.toastRemoved = L"Deleted:";
    s.toastUpToDate = L"Citron Launcher is up to date";
    s.toastUpdate = L"Citron Launcher {} is available";
    s.toastSettingsSaved = L"Settings saved";
    s.toastPathReset = L"Root directory reset to default";
    s.toastCancelled = L"Cancelled:";
    s.errLaunchTitle = L"Minecraft could not be started";
    s.errInstallTitle = L"Installation failed";
    s.errRemoveTitle = L"Version could not be removed";
    s.errDetails = L"Details";
    s.errGamingServices = L"Gaming Services is not installed.";
    s.dialogCancel = L"Cancel";
    s.envGamingServices = L"Gaming Services is not installed. Install it from the Microsoft Store to run Minecraft.";
    s.envHint = L"Open Store";
    s.minutesAgo = L"{} min ago";
    s.hoursAgo = L"{} h ago";
    s.justNow = L"just now";
    return s;
}

Strings german() {
    Strings s = english();
    s.tabPlay = L"Spielen";
    s.tabVersions = L"Versionen";
    s.tabSettings = L"Einstellungen";
    s.toggleTheme = L"Design wechseln";
    s.minimize = L"Minimieren";
    s.maximize = L"Maximieren";
    s.restore = L"Wiederherstellen";
    s.close = L"Schließen";
    s.launch = L"Starten";
    s.launching = L"Startet…";
    s.manageVersions = L"Versionen verwalten";
    s.noVersion = L"Keine Version";
    s.noVersionHint = L"Installiere eine Version auf der Seite Versionen, um zu starten.";
    s.downloadingUpper = L"WIRD GELADEN";
    s.searchVersion = L"Version suchen…";
    s.refresh = L"Aktualisieren";
    s.filterAll = L"Alle";
    s.filterRelease = L"Release";
    s.filterPreview = L"Vorschau";
    s.filterInstalled = L"Installiert";
    s.release = L"Release";
    s.preview = L"Vorschau";
    s.statusInstalled = L"Installiert";
    s.statusDownloaded = L"Heruntergeladen";
    s.statusNotDownloaded = L"Nicht heruntergeladen";
    s.statusDownloading = L"Wird geladen";
    s.statusVerifying = L"Wird geprüft";
    s.statusExtracting = L"Wird entpackt";
    s.statusRemoving = L"Wird gelöscht";
    s.statusActive = L"Aktiv";
    s.statusFailed = L"Fehlgeschlagen";
    s.statusUnavailable = L"Nicht verfügbar";
    s.download = L"Herunterladen";
    s.install = L"Installieren";
    s.cancel = L"Abbrechen";
    s.remove = L"Löschen";
    s.confirmRemove = L"Löschen bestätigen";
    s.retry = L"Erneut versuchen";
    s.dismiss = L"Ausblenden";
    s.noResults = L"Keine passenden Versionen.";
    s.versionsEmpty = L"Die Versionsliste konnte nicht geladen werden.";
    s.settingsUpper = L"EINSTELLUNGEN";
    s.pathsUpper = L"PFADE";
    s.aboutUpper = L"ÜBER";
    s.language = L"Sprache";
    s.languageSub = L"Sprache der Launcher-Oberfläche";
    s.closeOnLaunch = L"Launcher beim Spielstart schließen";
    s.closeOnLaunchSub = L"Der Launcher beendet sich, sobald Minecraft läuft";
    s.checkUpdates = L"Nach Launcher-Updates suchen";
    s.checkUpdatesSub = L"Benachrichtigen, wenn eine neue Citron-Version verfügbar ist";
    s.rootDir = L"Stammverzeichnis";
    s.browse = L"Durchsuchen…";
    s.installers = L"Installer";
    s.logs = L"Protokolle";
    s.apply = L"Anwenden";
    s.reset = L"Zurücksetzen";
    s.aboutSub = L"Ein minimaler Launcher für Minecraft Bedrock Edition";
    s.upToDate = L"Aktuell";
    s.updateAvailable = L"Update verfügbar";
    s.updateFailed = L"Prüfung fehlgeschlagen";
    s.notChecked = L"Noch nicht geprüft";
    s.checkedAgo = L"Geprüft {}";
    s.checkNow = L"Jetzt prüfen";
    s.checking = L"Prüft…";
    s.links = L"Links";
    s.toastLaunch = L"Minecraft wird gestartet";
    s.toastSelect = L"Aktive Version:";
    s.toastInstalled = L"Installiert:";
    s.toastDownloaded = L"Heruntergeladen:";
    s.toastRemoved = L"Gelöscht:";
    s.toastUpToDate = L"Citron Launcher ist aktuell";
    s.toastUpdate = L"Citron Launcher {} ist verfügbar";
    s.toastSettingsSaved = L"Einstellungen gespeichert";
    s.toastPathReset = L"Stammverzeichnis zurückgesetzt";
    s.toastCancelled = L"Abgebrochen:";
    s.errLaunchTitle = L"Minecraft konnte nicht gestartet werden";
    s.errInstallTitle = L"Installation fehlgeschlagen";
    s.errRemoveTitle = L"Version konnte nicht entfernt werden";
    s.errDetails = L"Details";
    s.errGamingServices = L"Gaming Services ist nicht installiert.";
    s.dialogCancel = L"Abbrechen";
    s.envGamingServices = L"Gaming Services ist nicht installiert. Installiere es aus dem Microsoft Store, um Minecraft zu starten.";
    s.envHint = L"Store öffnen";
    s.minutesAgo = L"vor {} Min.";
    s.hoursAgo = L"vor {} Std.";
    s.justNow = L"gerade eben";
    return s;
}

}

const Strings& stringsFor(std::string_view language) {
    static const Strings en = english();
    static const Strings de = german();
    return language == "de" ? de : en;
}

}
